package big2

// Generated by dectest. DO NOT EDIT

import "math/big"

var copynegateTests = []struct {
	id   string
	in   string
	out  string
	prec uint
	mode big.RoundingMode
}{
	// cpnx001 copynegate       +7.50  -> -7.50
	{"cpnx001", "+7.50", "-7.50", 9, big.ToPositiveInf},
	// Infinities
	// cpnx011 copynegate  Infinity    -> -Infinity
	{"cpnx011", "Infinity", "-Infinity", 9, big.ToPositiveInf},
	// cpnx012 copynegate  -Infinity   -> Infinity
	{"cpnx012", "-Infinity", "Infinity", 9, big.ToPositiveInf},
	// NaNs, 0 payload
	// cpnx021 copynegate         NaN  -> -NaN
	{"cpnx021", "NaN", "-NaN", 9, big.ToPositiveInf},
	// cpnx022 copynegate        -NaN  -> NaN
	{"cpnx022", "-NaN", "NaN", 9, big.ToPositiveInf},
	// cpnx023 copynegate        sNaN  -> -sNaN
	{"cpnx023", "sNaN", "-sNaN", 9, big.ToPositiveInf},
	// cpnx024 copynegate       -sNaN  -> sNaN
	{"cpnx024", "-sNaN", "sNaN", 9, big.ToPositiveInf},
	// NaNs, non-0 payload
	// cpnx031 copynegate       NaN13  -> -NaN13
	{"cpnx031", "NaN13", "-NaN13", 9, big.ToPositiveInf},
	// cpnx032 copynegate      -NaN13  -> NaN13
	{"cpnx032", "-NaN13", "NaN13", 9, big.ToPositiveInf},
	// cpnx033 copynegate      sNaN13  -> -sNaN13
	{"cpnx033", "sNaN13", "-sNaN13", 9, big.ToPositiveInf},
	// cpnx034 copynegate     -sNaN13  -> sNaN13
	{"cpnx034", "-sNaN13", "sNaN13", 9, big.ToPositiveInf},
	// cpnx035 copynegate       NaN70  -> -NaN70
	{"cpnx035", "NaN70", "-NaN70", 9, big.ToPositiveInf},
	// cpnx036 copynegate      -NaN70  -> NaN70
	{"cpnx036", "-NaN70", "NaN70", 9, big.ToPositiveInf},
	// cpnx037 copynegate      sNaN101 -> -sNaN101
	{"cpnx037", "sNaN101", "-sNaN101", 9, big.ToPositiveInf},
	// cpnx038 copynegate     -sNaN101 -> sNaN101
	{"cpnx038", "-sNaN101", "sNaN101", 9, big.ToPositiveInf},
	// finites
	// cpnx101 copynegate          7   -> -7
	{"cpnx101", "7", "-7", 9, big.ToPositiveInf},
	// cpnx102 copynegate         -7   -> 7
	{"cpnx102", "-7", "7", 9, big.ToPositiveInf},
	// cpnx103 copynegate         75   -> -75
	{"cpnx103", "75", "-75", 9, big.ToPositiveInf},
	// cpnx104 copynegate        -75   -> 75
	{"cpnx104", "-75", "75", 9, big.ToPositiveInf},
	// cpnx105 copynegate       7.50   -> -7.50
	{"cpnx105", "7.50", "-7.50", 9, big.ToPositiveInf},
	// cpnx106 copynegate      -7.50   -> 7.50
	{"cpnx106", "-7.50", "7.50", 9, big.ToPositiveInf},
	// cpnx107 copynegate       7.500  -> -7.500
	{"cpnx107", "7.500", "-7.500", 9, big.ToPositiveInf},
	// cpnx108 copynegate      -7.500  -> 7.500
	{"cpnx108", "-7.500", "7.500", 9, big.ToPositiveInf},
	// zeros
	// cpnx111 copynegate          0   -> -0
	{"cpnx111", "0", "-0", 9, big.ToPositiveInf},
	// cpnx112 copynegate         -0   -> 0
	{"cpnx112", "-0", "0", 9, big.ToPositiveInf},
	// cpnx113 copynegate       0E+4   -> -0E+4
	{"cpnx113", "0E+4", "-0E+4", 9, big.ToPositiveInf},
	// cpnx114 copynegate      -0E+4   -> 0E+4
	{"cpnx114", "-0E+4", "0E+4", 9, big.ToPositiveInf},
	// cpnx115 copynegate     0.0000   -> -0.0000
	{"cpnx115", "0.0000", "-0.0000", 9, big.ToPositiveInf},
	// cpnx116 copynegate    -0.0000   -> 0.0000
	{"cpnx116", "-0.0000", "0.0000", 9, big.ToPositiveInf},
	// cpnx117 copynegate      0E-141  -> -0E-141
	{"cpnx117", "0E-141", "-0E-141", 9, big.ToPositiveInf},
	// cpnx118 copynegate     -0E-141  -> 0E-141
	{"cpnx118", "-0E-141", "0E-141", 9, big.ToPositiveInf},
	// full coefficients, alternating bits
	// cpnx121 copynegate  268268268         -> -268268268
	{"cpnx121", "268268268", "-268268268", 9, big.ToPositiveInf},
	// cpnx122 copynegate  -268268268        -> 268268268
	{"cpnx122", "-268268268", "268268268", 9, big.ToPositiveInf},
	// cpnx123 copynegate  134134134         -> -134134134
	{"cpnx123", "134134134", "-134134134", 9, big.ToPositiveInf},
	// cpnx124 copynegate  -134134134        -> 134134134
	{"cpnx124", "-134134134", "134134134", 9, big.ToPositiveInf},
	// Nmax, Nmin, Ntiny
	// cpnx131 copynegate  9.99999999E+999   -> -9.99999999E+999
	{"cpnx131", "9.99999999E+999", "-9.99999999E+999", 9, big.ToPositiveInf},
	// cpnx132 copynegate  1E-999                     -> -1E-999
	{"cpnx132", "1E-999", "-1E-999", 9, big.ToPositiveInf},
	// cpnx133 copynegate  1.00000000E-999   -> -1.00000000E-999
	{"cpnx133", "1.00000000E-999", "-1.00000000E-999", 9, big.ToPositiveInf},
	// cpnx134 copynegate  1E-1007                    -> -1E-1007
	{"cpnx134", "1E-1007", "-1E-1007", 9, big.ToPositiveInf},
	// cpnx135 copynegate  -1E-1007                   -> 1E-1007
	{"cpnx135", "-1E-1007", "1E-1007", 9, big.ToPositiveInf},
	// cpnx136 copynegate  -1.00000000E-999  -> 1.00000000E-999
	{"cpnx136", "-1.00000000E-999", "1.00000000E-999", 9, big.ToPositiveInf},
	// cpnx137 copynegate  -1E-999                    -> 1E-999
	{"cpnx137", "-1E-999", "1E-999", 9, big.ToPositiveInf},
	// cpnx138 copynegate  -9.99999999E+999  -> 9.99999999E+999
	{"cpnx138", "-9.99999999E+999", "9.99999999E+999", 9, big.ToPositiveInf},
}
